In [5]:
import numpy

In [3]:
import cv2

In [6]:
n = numpy.arange(27) #Creates 1-D array of elements from 0 to 26.  

In [9]:
print(n)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


In [10]:
type(n)

numpy.ndarray

In [11]:
n.reshape(3,9) #Reshaping it to 3x9 matrix.

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [12]:
n.reshape(3,3,3) #Reshaping it ti 3x3x3 matrix.

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [13]:
import cv2

In [14]:
im_g = cv2.imread("small_img.png",0) #Since it is a gray scale image '0' value is passed.
im_g #It is a 3x5 pixel image.

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [15]:
im_g = cv2.imread("small_img.png",1) #Value '1' is passed to obtain B, G, R values respectively. 
print(im_g)

[[[187 187 187]
  [158 158 158]
  [104 104 104]
  [121 121 121]
  [143 143 143]]

 [[198 198 198]
  [125 125 125]
  [255 255 255]
  [255 255 255]
  [147 147 147]]

 [[209 209 209]
  [134 134 134]
  [255 255 255]
  [ 97  97  97]
  [182 182 182]]]


In [16]:
cv2.imwrite("new_small_img.png",im_g)

True

In [18]:
im_g = cv2.imread("small_img.png",0)
print(im_g)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [19]:
im_g[0:2,2:4] #indexing and slicing numpy arrays.

array([[104, 121],
       [255, 255]], dtype=uint8)

In [20]:
im_g[:,3:4] #Slicing only the 3rd column.

array([[121],
       [255],
       [ 97]], dtype=uint8)

In [21]:
im_g[2,4] #Slicing only the last element.

182

In [22]:
for i in im_g:  #Accessing rows in numpy array.
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [23]:
for i in im_g.T:  #Accessing columns in numpy array.
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [24]:
for i in im_g.flat:  #Accessing each elements in numpy array.
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [25]:
ims = numpy.hstack((im_g,im_g)) #To stack horizontally two or more numpy arrays, a tuple must be passed.
ims

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [27]:
ims = numpy.hstack((im_g,im_g,im_g))
print(ims)

[[187 158 104 121 143 187 158 104 121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182 209 134 255  97 182]]


In [28]:
ims = numpy.vstack((im_g,im_g,im_g)) #To stack vertically two or more numpy arrays, a tuple must be passed.
print(ims)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [37]:
lst = numpy.hsplit(ims,5) #To split numpy array horizontally where '5' represents no.of splits.
lst

[array([[187],
        [198],
        [209],
        [187],
        [198],
        [209],
        [187],
        [198],
        [209]], dtype=uint8), array([[158],
        [125],
        [134],
        [158],
        [125],
        [134],
        [158],
        [125],
        [134]], dtype=uint8), array([[104],
        [255],
        [255],
        [104],
        [255],
        [255],
        [104],
        [255],
        [255]], dtype=uint8), array([[121],
        [255],
        [ 97],
        [121],
        [255],
        [ 97],
        [121],
        [255],
        [ 97]], dtype=uint8), array([[143],
        [147],
        [182],
        [143],
        [147],
        [182],
        [143],
        [147],
        [182]], dtype=uint8)]

In [34]:
lst = numpy.hsplit(ims,3) #To split numpy array horizontally where '3' represents no.of splits.
print(lst) #Since ims has 5 columns it cannot be divided equally to 3 splits.

ValueError: array split does not result in an equal division

In [36]:
lst = numpy.vsplit(ims,3) #To split numpy array vertically where '3' represents no.of splits.
lst

[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8)]

In [38]:
type(lst)

list

In [39]:
lst[0]

array([[187],
       [198],
       [209],
       [187],
       [198],
       [209],
       [187],
       [198],
       [209]], dtype=uint8)